name: BuycraftX
main: net.buycraft.plugin.bukkit.BuycraftPlugin
version: ${project.version}
author: Buycraft
authors: [AlexMl]
api-version: "1.13"
commands:
  tebex:
    aliases: [buycraft]
    description: Main command for the Tebex plugin.